# Generated by Django 5.2.8 on 2025-12-27 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='serial_number',
            field=models.IntegerField(unique=True),
        ),
    ]
