# Generated by Django 5.2.8 on 2025-12-27 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0003_historicalstudent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalstudent',
            name='serial_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='student',
            name='serial_number',
            field=models.IntegerField(),
        ),
    ]
