# Generated by Django 5.2.8 on 2026-04-08 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tourplan', '0004_alter_historicalstudent_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='participation',
        ),
        migrations.RemoveField(
            model_name='student',
            name='serial_number',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='student_semester',
        ),
        migrations.DeleteModel(
            name='HistoricalStudent',
        ),
    ]
