# Generated by Django 5.2.8 on 2025-12-08 04:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_sitepage_site_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='LoanTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Interest rate in percentage', max_digits=5)),
                ('amount_limit', models.DecimalField(decimal_places=2, help_text='Maximum loan amount', max_digits=12)),
                ('required_documents', models.JSONField(default=list, help_text='List of required document types')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Loan Type',
                'verbose_name_plural': 'Loan Types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('duration_months', models.IntegerField()),
                ('purpose', models.TextField()),
                ('monthly_income', models.DecimalField(decimal_places=2, max_digits=12)),
                ('address', models.TextField()),
                ('citizenship_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('info_requested', 'Info Requested'), ('info_provided', 'Info Provided'), ('documents_verified', 'Documents Verified'), ('salary_verified', 'Salary Verified'), ('proposal_approved', 'Proposal Approved'), ('final_review', 'Final Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('status_history', models.JSONField(default=list)),
                ('comments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to=settings.AUTH_USER_MODEL)),
                ('officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_applications', to=settings.AUTH_USER_MODEL)),
                ('loan_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.loantypes')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
