# Generated by Django 5.2.8 on 2025-12-08 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_document_loantypes_application'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applicant',
        ),
        migrations.RemoveField(
            model_name='application',
            name='loan_type',
        ),
        migrations.RemoveField(
            model_name='application',
            name='officer',
        ),
        migrations.DeleteModel(
            name='Document',
        ),
        migrations.DeleteModel(
            name='LoanTypes',
        ),
        migrations.DeleteModel(
            name='Application',
        ),
    ]
