# Generated by Django 5.2.8 on 2025-12-16 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_remove_application_applicant_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sitepage",
            name="allowed_income_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=50,
                help_text="Maximum loan amount as % of applicant monthly income",
                max_digits=5,
            ),
        ),
    ]
