# Generated by Django 5.2.8 on 2025-12-05 10:57

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='applicant full name')),
                ('last_name', models.CharField(max_length=50, verbose_name='applicant full name')),
                ('full_name', models.CharField(max_length=150, verbose_name='applicant full name')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('loan_officer', 'Loan Officer'), ('senior_officer', 'Senior Officer')], default='customer', max_length=50, verbose_name='applicant role')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='applicant email')),
                ('phone', models.CharField(max_length=15, verbose_name='applicant phone no')),
                ('is_active', models.BooleanField(default=True, verbose_name='applicant active status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='applicant date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, verbose_name='gender of the applicant')),
                ('nationality', models.CharField(default='Nepali', max_length=50, verbose_name='applicant nation')),
                ('permanent_address', models.TextField(blank=True, verbose_name='applicant permanent address')),
                ('temporary_address', models.TextField(blank=True, verbose_name='applicant temporary address')),
                ('occupation', models.CharField(blank=True, choices=[('individual', 'Individual Borrower'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('self_employed', 'Self employed'), ('farmer', 'Farmer')], max_length=50, verbose_name='applicant occupation')),
                ('employer_name', models.CharField(blank=True, max_length=100, verbose_name='applicant employer if any')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='applicant income')),
                ('citizenship_number', models.CharField(blank=True, max_length=50, verbose_name='applicant citizenship number')),
                ('national_id_number', models.CharField(blank=True, max_length=50, verbose_name='applicant national id number')),
                ('pan_number', models.CharField(blank=True, max_length=50, verbose_name='applicant pan number')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('citizenship_front_url', models.URLField(blank=True)),
                ('citizenship_back_url', models.URLField(blank=True)),
                ('passport_photo_url', models.URLField(blank=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('kyc_verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kyc_verifications', to=settings.AUTH_USER_MODEL)),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
