# Generated by Django 5.2.8 on 2025-12-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='citizenship_back_url',
            field=models.FileField(blank=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='citizenship_front_url',
            field=models.FileField(blank=True, upload_to='kyc'),
        ),
        migrations.AlterField(
            model_name='user',
            name='kyc_verified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_photo_url',
            field=models.FileField(blank=True, upload_to='kyc'),
        ),
    ]
