# Generated by Django 5.2.8 on 2025-12-20 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_citizenship_back_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='kyc_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
