# Generated by Django 5.2.8 on 2025-12-26 09:51

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_kyc_verified_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalUser',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('first_name', models.CharField(max_length=50, verbose_name='applicant first name')),
                ('last_name', models.CharField(max_length=50, verbose_name='applicant last name')),
                ('full_name', models.CharField(max_length=150, verbose_name='applicant full name')),
                ('role', models.CharField(choices=[('customer', 'Customer'), ('admin', 'Admin'), ('loan_officer', 'Loan Officer'), ('senior_officer', 'Senior Officer')], default='customer', max_length=50, verbose_name='applicant role')),
                ('email', models.EmailField(db_index=True, max_length=254, verbose_name='applicant email')),
                ('phone', models.CharField(max_length=15, verbose_name='applicant phone no')),
                ('is_active', models.BooleanField(default=True, verbose_name='applicant active status')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='applicant date of birth')),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=50, verbose_name='gender of the applicant')),
                ('nationality', models.CharField(default='Nepali', max_length=50, verbose_name='applicant nation')),
                ('permanent_address', models.TextField(blank=True, verbose_name='applicant permanent address')),
                ('temporary_address', models.TextField(blank=True, verbose_name='applicant temporary address')),
                ('occupation', models.CharField(blank=True, choices=[('individual', 'Individual Borrower'), ('business_owner', 'Business Owner'), ('student', 'Student'), ('self_employed', 'Self employed'), ('farmer', 'Farmer')], max_length=50, verbose_name='applicant occupation')),
                ('employer_name', models.CharField(blank=True, max_length=100, verbose_name='applicant employer if any')),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='applicant income')),
                ('citizenship_number', models.CharField(blank=True, max_length=50, verbose_name='applicant citizenship number')),
                ('national_id_number', models.CharField(blank=True, max_length=50, verbose_name='applicant national id number')),
                ('pan_number', models.CharField(blank=True, max_length=50, verbose_name='applicant pan number')),
                ('kyc_status', models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('kyc_verified_at', models.DateTimeField(blank=True, null=True)),
                ('citizenship_front_url', models.TextField(blank=True, max_length=100)),
                ('citizenship_back_url', models.TextField(blank=True, max_length=100)),
                ('passport_photo_url', models.TextField(blank=True, max_length=100)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('kyc_verified_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical User',
                'verbose_name_plural': 'historical Users',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
