# Generated by Django 5.2.8 on 2026-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified?'),
        ),
        migrations.AddField(
            model_name='historicaluser',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='mobile number verified?'),
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False, verbose_name='email verified?'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_verified',
            field=models.BooleanField(default=False, verbose_name='mobile number verified?'),
        ),
    ]
