# Generated by Django 5.2.8 on 2025-12-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('citizenship_front', 'Citizenship Certificate (Front)'), ('citizenship_back', 'Citizenship Certificate (Back)'), ('salary_slip', 'Salary Slips'), ('bank_statement', 'Bank Statements'), ('business_registration', 'Business Registration'), ('property_document', 'Property Documents'), ('admission_letter', 'Admission Letter'), ('guarantor_document', 'Guarantor Documents')], default='citizenship_front', max_length=50),
        ),
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='media/documents/'),
        ),
        migrations.AddField(
            model_name='document',
            name='verification_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
