# Generated by Django 5.2.8 on 2025-12-10 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_document_document_type_document_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='required_documents_status',
            field=models.JSONField(default=dict, help_text='Tracks required and uploaded documents'),
        ),
    ]
