# Generated by Django 5.2.8 on 2025-12-10 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_application_required_documents_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='application',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.application'),
        ),
    ]
