# Generated by Django 5.2.8 on 2025-12-10 09:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0004_document_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='loans.application'),
        ),
    ]
