# Generated by Django 5.2.8 on 2025-12-10 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0007_alter_document_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='required_documents_status',
        ),
        migrations.RemoveField(
            model_name='document',
            name='application',
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(default='default.pdf', upload_to='media/documents/'),
        ),
    ]
