# Generated by Django 5.2.8 on 2025-12-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0009_document_application'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
