# Generated by Django 5.2.8 on 2026-01-07 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0014_approvedloans_approved_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('citizenship_front', 'Citizenship Certificate (Front)'), ('citizenship_back', 'Citizenship Certificate (Back)'), ('salary_slip', 'Salary Slips'), ('bank_statement', 'Bank Statements'), ('business_registration', 'Business Registration'), ('property_document', 'Property Documents'), ('admission_letter', 'Admission Letter'), ('id_proof', 'ID Proof')], default='citizenship_front', max_length=50),
        ),
        migrations.AlterField(
            model_name='historicaldocument',
            name='document_type',
            field=models.CharField(choices=[('citizenship_front', 'Citizenship Certificate (Front)'), ('citizenship_back', 'Citizenship Certificate (Back)'), ('salary_slip', 'Salary Slips'), ('bank_statement', 'Bank Statements'), ('business_registration', 'Business Registration'), ('property_document', 'Property Documents'), ('admission_letter', 'Admission Letter'), ('id_proof', 'ID Proof')], default='citizenship_front', max_length=50),
        ),
    ]
