# Generated by Django 5.2.8 on 2026-01-14 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0015_alter_document_document_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaldocument',
            name='is_additional',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('application', 'document_type')},
        ),
    ]
