# Generated by Django 5.2.8 on 2026-01-14 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0016_document_is_additional_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together=set(),
        ),
    ]
