# Generated by Django 5.2.8 on 2026-01-14 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0017_alter_document_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='document',
            unique_together={('application', 'document_type')},
        ),
    ]
