# Generated by Django 5.2.8 on 2026-01-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0019_alter_document_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalrepayment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='repayment',
            name='amount_paid',
        ),
        migrations.AlterField(
            model_name='historicalrepayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('late', 'Late')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='repayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('partial', 'Partial'), ('paid', 'Paid'), ('late', 'Late')], default='pending', max_length=20),
        ),
    ]
