# Generated by Django 5.2.8 on 2026-01-20 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0020_remove_historicalrepayment_amount_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrepayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
        migrations.AddField(
            model_name='repayment',
            name='amount_paid',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=16),
        ),
    ]
