# Generated by Django 4.2.30 on 2026-05-08 02:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycverification',
            name='citizenship',
        ),
        migrations.RemoveField(
            model_name='kycverification',
            name='selfie',
        ),
        migrations.AddField(
            model_name='kycverification',
            name='blink_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='citizenship_image',
            field=models.ImageField(default='2026-05-08', upload_to='kyc/citizenship/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='kycverification',
            name='left_turn_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='right_turn_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='kycverification',
            name='selfie_image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='kyc/selfie/'),
            preserve_default=False,
        ),
    ]
