# Generated by Django 4.2.30 on 2026-05-10 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kyc', '0002_remove_kycverification_citizenship_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycverification',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kyc_verification_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
